In [1]:
import pandas as pd
#import xlrd
import os
import re
import datetime

In [2]:
data_file_path = 'C:\\Users\\김진태\\Jupyter_Folder\\Data\\order20180101to20190430.xlsx'
df = pd.read_excel(data_file_path, Sheet_name='주문 고객 현황')
"""
df2 = get_filter_dataframe(df)

#판매유형 별 숫자 카운트 딕셔너리
os_cnt_dic = {'신규':0, '기타':0, '업셀':0, '추가':0}
for row in df2.values:
    os_cnt_dic[row[5]] += 1
print(os_cnt_dic)

# 유일한 값을 발췌한다
df2['판매유형'].unique()
"""

"\ndf2 = get_filter_dataframe(df)\n\n#판매유형 별 숫자 카운트 딕셔너리\nos_cnt_dic = {'신규':0, '기타':0, '업셀':0, '추가':0}\nfor row in df2.values:\n    os_cnt_dic[row[5]] += 1\nprint(os_cnt_dic)\n\n# 유일한 값을 발췌한다\ndf2['판매유형'].unique()\n"

In [3]:
#df.shape[0]
df.head(3)

,순번,구분,주담당채널,주담당부서,주담당자,영업채널명,영업부서명,영업담당자명,고객명,사업자/주민,...,프로모션명,패키지 Pack 여부,전자세금계산서발행여부,관계사발행,기회시작일,경과일,활동건수,영업유형,매출국가,정산분류
0,1,지점,"서울3,4 IT코디센터(강원)",강원지점,김진호A,강원지점,강원지점,김진호A,(주) 푸드누리,215-86-56153,...,NaN,NaN,0.0,1.0,2018-08-28,0.0,0.0,인바운드,대한민국,ETC
1,2,지점,"서울3,4 IT코디센터(강원)",강원지점,김진호A,강원지점,강원지점,김진호A,(주) 푸드누리,215-86-56153,...,NaN,NaN,0.0,1.0,2018-08-28,0.0,0.0,기존고객,대한민국,ETC
2,3,지점,"서울3,4 IT코디센터(강원)",강원지점,김진호A,강원지점,강원지점,김진호A,(주) 푸드누리,215-86-56153,...,NaN,NaN,0.0,1.0,2018-08-28,0.0,0.0,인바운드,대한민국,ETC

In [5]:
df['상품명'].unique()

array(['Smart UC(Smart A 고객용)', 'Smart Office',
       '기업용 Smart A Cloud edition', 'SmartA Premium Package',
       'Bizbox Alpha Cloud', 'IDC서비스', '(신)iCUBE Cloud Edition',
       'bizbox Cloud', 'ICUBE/GW 클라우드서버', 'ICUBE 클라우드서버', 'IU/GW 클라우드서버',
       'GW 클라우드서버', 'IU 클라우드서버', '세무용 Smart A Cloud edition',
       'ICUBE/IU 클라우드서버', 'iPlus Cloud Edition', '클라우드서버', '클라우드 외부서비스',
       'iCube Private', 'Private Cloud', 'WEHAGO(기업용)', 'iU Private',
       'iCUBE-G20 Cloud Edition', '클라우드백업서버', nan], dtype=object)

In [6]:
# 상품명
product_category = {'GW 클라우드서버', 'ICUBE/GW 클라우드서버', 'IU/GW 클라우드서버'}  # 집합(중복값 불허)
df2 = df[df['상품명'].isin(product_category)]
print('조회 건수 : %d건' % df2.shape[0])
df2.head(3)

조회 건수 : 2726건

,순번,구분,주담당채널,주담당부서,주담당자,영업채널명,영업부서명,영업담당자명,고객명,사업자/주민,...,프로모션명,패키지 Pack 여부,전자세금계산서발행여부,관계사발행,기회시작일,경과일,활동건수,영업유형,매출국가,정산분류
155,156,지점,"서울3,4 IT코디센터(강원)",강원지점,박종현,강원지점,강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,...,NaN,NaN,0.0,1.0,2019-02-26,0.0,0.0,기존고객,대한민국,ETC
156,157,지점,"서울3,4 IT코디센터(강원)",강원지점,박종현,강원지점,강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,...,NaN,NaN,0.0,1.0,2019-02-26,0.0,0.0,기존고객,대한민국,ETC
157,158,지점,"서울3,4 IT코디센터(강원)",강원지점,박종현,강원지점,강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,...,NaN,NaN,0.0,1.0,2019-02-26,0.0,0.0,기존고객,대한민국,ETC

In [7]:
#df['단위상품명'].unique()
print(df2.head(3).keys())
unit_product_category = {'클라우드서버(기본)'}  # 집합(중복값 불허)
df2 = df2[df2['단위상품명'].isin(unit_product_category)]
print('조회 건수 : %d건' % df2.shape[0])
df2.head(3)

Index(['순번', '구분', '주담당채널', '주담당부서', '주담당자', '영업채널명', '영업부서명', '영업담당자명', '고객명',
       '사업자/주민', '주문번호', '주문일자', '주문상태', '주문현황', '납입구분', '상품명', '단위상품명', '사용자',
       '공급가', '금액(VAT별도)', '반품금액(VAT별도)', '수주잔액(VAT별도)', '전화번호', 'FAX', '비고',
       '기타', '주소', '고객구분', '세무구분', '판매유형', '영업형태', '세무대리증빙', '약정기간', '구매증빙',
       '프로모션명', '패키지 Pack 여부', '전자세금계산서발행여부', '관계사발행', '기회시작일', '경과일', '활동건수',
       '영업유형', '매출국가', '정산분류'],
      dtype='object')
조회 건수 : 762건

,순번,구분,주담당채널,주담당부서,주담당자,영업채널명,영업부서명,영업담당자명,고객명,사업자/주민,...,프로모션명,패키지 Pack 여부,전자세금계산서발행여부,관계사발행,기회시작일,경과일,활동건수,영업유형,매출국가,정산분류
157,158,지점,"서울3,4 IT코디센터(강원)",강원지점,박종현,강원지점,강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,...,NaN,NaN,0.0,1.0,2019-02-26,0.0,0.0,기존고객,대한민국,ETC
161,162,지점,"서울3,4 IT코디센터(강원)",강원지점,박종현,강원지점,강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,...,NaN,NaN,0.0,1.0,2019-02-26,0.0,0.0,기존고객,대한민국,ETC
179,180,지점,"서울3,4 IT코디센터(강원)",강원지점,윤명현,강원지점,강원지점,윤명현,강릉에코파워주식회사,226-81-50381,...,NaN,NaN,0.0,1.0,2018-07-11,0.0,0.0,기존고객,대한민국,ETC

In [41]:
df2['판매유형'].value_counts()

신규            447
기타            162
추가             61
보상(UP,재계약)     52
재주문            40
Name: 판매유형, dtype: int64

In [42]:
#df['단위상품명'].unique()
print(df2.head(3).keys())
sale_type_category = {'신규'}  # 집합(중복값 불허)
df2 = df2[df2['판매유형'].isin(sale_type_category)]
print('조회 건수 : %d건' % df2.shape[0])
df2.head(3)

Index(['순번', '구분', '주담당채널', '주담당부서', '주담당자', '영업채널명', '영업부서명', '영업담당자명', '고객명',
       '사업자/주민', '주문번호', '주문일자', '주문상태', '주문현황', '납입구분', '상품명', '단위상품명', '사용자',
       '공급가', '금액(VAT별도)', '반품금액(VAT별도)', '수주잔액(VAT별도)', '전화번호', 'FAX', '비고',
       '기타', '주소', '고객구분', '세무구분', '판매유형', '영업형태', '세무대리증빙', '약정기간', '구매증빙',
       '프로모션명', '패키지 Pack 여부', '전자세금계산서발행여부', '관계사발행', '기회시작일', '경과일', '활동건수',
       '영업유형', '매출국가', '정산분류'],
      dtype='object')
조회 건수 : 447건

,순번,구분,주담당채널,주담당부서,주담당자,영업채널명,영업부서명,영업담당자명,고객명,사업자/주민,...,프로모션명,패키지 Pack 여부,전자세금계산서발행여부,관계사발행,기회시작일,경과일,활동건수,영업유형,매출국가,정산분류
157,158,지점,"서울3,4 IT코디센터(강원)",강원지점,박종현,강원지점,강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,...,NaN,NaN,0.0,1.0,2019-02-26,0.0,0.0,기존고객,대한민국,ETC
161,162,지점,"서울3,4 IT코디센터(강원)",강원지점,박종현,강원지점,강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,...,NaN,NaN,0.0,1.0,2019-02-26,0.0,0.0,기존고객,대한민국,ETC
179,180,지점,"서울3,4 IT코디센터(강원)",강원지점,윤명현,강원지점,강원지점,윤명현,강릉에코파워주식회사,226-81-50381,...,NaN,NaN,0.0,1.0,2018-07-11,0.0,0.0,기존고객,대한민국,ETC

In [43]:
read_columns = ['주담당채널', '영업채널명', '영업담당자명', '고객명', '사업자/주민', '주문일자', '주문상태',
                '주문현황', '납입구분', '상품명', '단위상품명', '사용자', '공급가', '금액(VAT별도)', '판매유형', '기회시작일']

df3 = df2[read_columns]
print('조회 건수 : %d건' % df3.shape[0])
df3.head(3)

조회 건수 : 447건

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,사용자,공급가,금액(VAT별도),판매유형,기회시작일
157,"서울3,4 IT코디센터(강원)",강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,2019-02-26,주문완료,주문완료,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,3048000,신규,2019-02-26
161,"서울3,4 IT코디센터(강원)",강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,2019-02-26,주문완료,주문완료,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,1200000,신규,2019-02-26
179,"서울3,4 IT코디센터(강원)",강원지점,윤명현,강릉에코파워주식회사,226-81-50381,2018-07-11,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,2268000,신규,2018-07-11

In [44]:
# IT코디센터는 C로 대리점은 B로 새로운칼럼에 추가한다
channel_series = df3.apply(lambda v: 'C' if v[1].endswith('IT코디센터') else 'B', axis=1)   #
#df3['CB'] = channel_series
df3.loc[:, 'CB'] = channel_series
df3.head(3)

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,사용자,공급가,금액(VAT별도),판매유형,기회시작일,CB
157,"서울3,4 IT코디센터(강원)",강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,2019-02-26,주문완료,주문완료,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,3048000,신규,2019-02-26,B
161,"서울3,4 IT코디센터(강원)",강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,2019-02-26,주문완료,주문완료,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,1200000,신규,2019-02-26,B
179,"서울3,4 IT코디센터(강원)",강원지점,윤명현,강릉에코파워주식회사,226-81-50381,2018-07-11,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,2268000,신규,2018-07-11,B

In [45]:
df3['CB'].value_counts()

C    337
B    110
Name: CB, dtype: int64

In [46]:
# 년도-월까지 잘라서 YM 칼럼에 저장한다
df3.loc[:,'YM'] = df3['주문일자'].str[0:7]
df3.head(3)

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,사용자,공급가,금액(VAT별도),판매유형,기회시작일,CB,YM
157,"서울3,4 IT코디센터(강원)",강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,2019-02-26,주문완료,주문완료,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,3048000,신규,2019-02-26,B,2019-02
161,"서울3,4 IT코디센터(강원)",강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,2019-02-26,주문완료,주문완료,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,1200000,신규,2019-02-26,B,2019-02
179,"서울3,4 IT코디센터(강원)",강원지점,윤명현,강릉에코파워주식회사,226-81-50381,2018-07-11,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,2268000,신규,2018-07-11,B,2018-07

In [48]:
# 월별 수주 건수 확인
s1 = df3['YM'].value_counts().sort_index(ascending=True)
print(s1)

2018-01    11
2018-02    27
2018-03    32
2018-04    28
2018-05    28
2018-06    22
2018-07    28
2018-08    24
2018-09    28
2018-10    28
2018-11    36
2018-12    56
2019-01    19
2019-02    31
2019-03    23
2019-04    26
Name: YM, dtype: int64

In [54]:
#s1.keys()
#s1.values
s1

2018-01    11
2018-02    27
2018-03    32
2018-04    28
2018-05    28
2018-06    22
2018-07    28
2018-08    24
2018-09    28
2018-10    28
2018-11    36
2018-12    56
2019-01    19
2019-02    31
2019-03    23
2019-04    26
Name: YM, dtype: int64

In [55]:
# 영업채널별 전체 발주 건수
df3['영업채널명'].value_counts().sort_values(ascending=False)

서울2 IT코디센터     61
서울1 IT코디센터     55
서울4 IT코디센터     36
서울3 IT코디센터     33
부산IT코디센터       26
인천IT코디센터       21
대구/경북IT코디센터    19
천안IT코디센터       18
울산IT코디센터       15
다우아이티          14
중부IT코디센터       13
도움이티에스         13
제주지점           12
경기IT코디센터       12
경남IT코디센터       11
아이원소프트뱅크       10
지아이소프트랩        10
이젠솔루션           9
전주IT코디센터        9
호남IT코디센터        8
유니에스아이          6
비아이             6
비즈웰             6
비앤에스컴퍼니         5
신원이노베이션         4
하이텍라인           4
다인정보            3
강원지점            3
엠아이솔루션          2
디엠솔루션           2
유비이앤씨           1
Name: 영업채널명, dtype: int64

In [56]:
# 선택한 월에 발주한 영업채널 별 건수 조회
df4 = df3[df3['YM']=='2019-04'] #2018-08
df4['영업채널명'].value_counts().sort_values(ascending=False).head(100)

서울1 IT코디센터    7
서울3 IT코디센터    6
중부IT코디센터      3
아이원소프트뱅크      2
제주지점          2
경남IT코디센터      2
하이텍라인         2
도움이티에스        1
천안IT코디센터      1
Name: 영업채널명, dtype: int64

In [87]:
df3.head(3)

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,사용자,공급가,금액(VAT별도),판매유형,기회시작일,CB,YM
157,"서울3,4 IT코디센터(강원)",강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,2019-02-26,주문완료,주문완료,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,3048000,신규,2019-02-26,B,2019-02
161,"서울3,4 IT코디센터(강원)",강원지점,윤명현,(재)스크립스코리아항체연구원,221-82-13262,2019-02-26,주문완료,주문완료,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,1200000,신규,2019-02-26,B,2019-02
179,"서울3,4 IT코디센터(강원)",강원지점,윤명현,강릉에코파워주식회사,226-81-50381,2018-07-11,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,2268000,신규,2018-07-11,B,2018-07

In [103]:
# 인덱스를 YM(년월)으로 바꾼다
df4 = df3.copy()
#df4.set_index('YM')['2018-06':'2018-06']
df4.set_index('YM', inplace=True)
df4.sort_index(ascending=True, inplace=True)
print('조회 건수 : %d건' % df4.shape[0])
df4.head(3)

조회 건수 : 447건

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,사용자,공급가,금액(VAT별도),판매유형,기회시작일,CB
YM,,,,,,,,,,,,,,,,,
2018-01,중부IT코디센터,중부IT코디센터,성민석,(주)다산에너지,314-86-53230,2018-01-16,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,4320000,신규,2018-01-16,C
2018-01,NaN,다우아이티,오서연,(주)이뮨메드,221-81-16466,2018-01-31,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,5160000,신규,2018-01-31,B
2018-01,"서울1,2 IT코디센터",서울2 IT코디센터,이기학,(주)코닉글로리,114-86-57392,2018-01-25,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,4920000,신규,2018-01-25,C

In [121]:
# 인덱스로 시작:종료 구간을 지정하여 조회한다
print(df4.index.unique())
#df4['2018-06':'2018-06']
df4['2018-01':'2018-02'][{'영업채널명', '고객명', '주문일자', '상품명'}].head(3)

Index(['2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06',
       '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12',
       '2019-01', '2019-02', '2019-03', '2019-04'],
      dtype='object', name='YM')

              고객명       영업채널명        주문일자              상품명
YM
2018-01  (주)다산에너지    중부IT코디센터  2018-01-16  ICUBE/GW 클라우드서버
2018-01   (주)이뮨메드       다우아이티  2018-01-31  ICUBE/GW 클라우드서버
2018-01  (주)코닉글로리  서울2 IT코디센터  2018-01-25  ICUBE/GW 클라우드서버

In [123]:
df4.sort_values(by=['주문일자', '고객명'], ascending=True).head(3)

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,사용자,공급가,금액(VAT별도),판매유형,기회시작일,CB
YM,,,,,,,,,,,,,,,,,
2018-01,"서울1,2 IT코디센터",서울2 IT코디센터,이승준,(주)에이앤씨콜렉티브,211-86-97910,2018-01-11,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,1920000,신규,2018-01-11,C
2018-01,중부IT코디센터,중부IT코디센터,성민석,(주)다산에너지,314-86-53230,2018-01-16,주문완료,발송중,일시납,ICUBE/GW 클라우드서버,클라우드서버(기본),1.0,0,4320000,신규,2018-01-16,C
2018-01,NaN,하이텍라인,이지현A,(주)동남기계,610-81-22436,2018-01-18,주문완료,주문완료,일시납,GW 클라우드서버,클라우드서버(기본),1.0,0,1800000,신규,2018-01-18,B