In [1]:
import pandas as pd
import xlrd
import os

In [2]:
os.getcwd()

'C:\\Users\\김진태'

In [3]:
excel_file = "C:\\Temp\\NsmData\data20190417.xlsx"
if not os.path.exists(excel_file): 
    print(excel_file + ' file not found!! ')

In [4]:
df = pd.read_excel(excel_file, Sheet_name='Sheet1')

In [5]:
df.keys()

Index(['순번', '구분', '주담당채널', '주담당부서', '주담당자', '영업채널명', '영업부서명', '영업담당자명', '고객명',
       '사업자/주민', '주문번호', '주문일자', '주문상태', '주문현황', '납입구분', '상품명', '단위상품명', '사용자',
       '공급가', '금액(VAT별도)', '반품금액(VAT별도)', '수주잔액(VAT별도)', '전화번호', 'FAX', '비고',
       '기타', '주소', '고객구분', '세무구분', '판매유형', '영업형태', '세무대리증빙', '약정기간', '구매증빙',
       '프로모션명', '패키지 Pack 여부', '전자세금계산서발행여부', '관계사발행', '기회시작일', '경과일', '활동건수',
       '영업유형', '매출국가', '정산분류', '영업실적율', '영업실적금액', '구분.1', '부서명', '사원명',
       '영업실적율.1', '영업실적금액.1', '구분.2', '부서명.1', '사원명.1'],
      dtype='object')

In [6]:
df1 = df[['주담당채널', '영업채널명', '영업담당자명', '고객명', '사업자/주민', '주문일자', '주문상태', '주문현황', '납입구분', '상품명', '단위상품명', '공급가', '금액(VAT별도)', '판매유형', '기회시작일' ]]

In [7]:
product_category = {'ICUBE 클라우드서버', 'Bizbox Alpha Cloud'}

In [64]:
'ICUBE 클라우드서버' in product_category

True

In [65]:
df1['상품명'].apply(lambda x : x in product_category)

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31     True
32     True
33     True
34     True
35     True
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43     True
44     True
45     True
46     True
47     True
48     True
49     True
50    False
51    False
52    False
53    False
54    False
Name: 상품명, dtype: bool

In [66]:
#df1['상품명']
df1['상품명'].isin(product_category)

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31     True
32     True
33     True
34     True
35     True
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43     True
44     True
45     True
46     True
47     True
48     True
49     True
50    False
51    False
52    False
53    False
54    False
Name: 상품명, dtype: bool

In [8]:
df2 = df1[df1['상품명'].isin(product_category)]

In [9]:
df2

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,공급가,금액(VAT별도),판매유형,기회시작일
3,"서울1,2 IT코디센터",서울1 IT코디센터,김민지,(주)지엔오션,403-87-00573,2019-04-17,주문완료,주문완료,일시납,Bizbox Alpha Cloud,"엔진(기본, 웹메일)",12000000,0,업셀,2019-04-17
4,"서울1,2 IT코디센터",서울1 IT코디센터,김민지,(주)지엔오션,403-87-00573,2019-04-17,주문완료,주문완료,일시납,Bizbox Alpha Cloud,유저 라이선스(월납),200000,100000,업셀,2019-04-17
5,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1200000,신규,2019-04-17
6,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백신서비스(서버전용백신),0,360000,신규,2019-04-17
7,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
8,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
9,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
31,중부IT코디센터,중부IT코디센터,성민석,주식회사 웰텍,314-86-60600,2019-04-17,진행중,진행중,일시납,Bizbox Alpha Cloud,유저 라이선스(월납),20000,12000,추가,2019-04-17
32,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1200000,신규,2019-04-17
33,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
34,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
35,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
43,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1080000,신규,2019-04-17
44,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
45,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
46,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,3369600,신규,2019-04-17
47,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
48,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
49,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17

In [16]:
groupby_columns_list = ['영업채널명', '영업담당자명', '사업자/주민', '고객명', '상품명', '판매유형', '기회시작일']

In [22]:
df2.groupby(groupby_columns_list).size().reset_index(name='count')

,영업채널명,영업담당자명,사업자/주민,고객명,상품명,판매유형,기회시작일,count
0,서울1 IT코디센터,김민지,403-87-00573,(주)지엔오션,Bizbox Alpha Cloud,업셀,2019-04-17,2
1,서울1 IT코디센터,송재웅,120-87-84760,주식회사 퀄슨,ICUBE 클라우드서버,신규,2019-04-17,5
2,엠아이솔루션,전지원,133-81-19093,디와이엘라센(주),ICUBE 클라우드서버,신규,2019-04-17,3
3,유니에스아이,박준호,211-88-68802,유한회사 알지피코리아,ICUBE 클라우드서버,신규,2019-04-17,4
4,중부IT코디센터,성민석,314-86-60600,주식회사 웰텍,Bizbox Alpha Cloud,추가,2019-04-17,1
5,호남IT코디센터,김기성,411-82-11004,(재)녹색에너지연구원,ICUBE 클라우드서버,신규,2019-04-17,4

In [24]:
grouped_df = df2.groupby(groupby_columns_list)

In [44]:
grouped_df.sum().reset_index()

,영업채널명,영업담당자명,사업자/주민,고객명,상품명,판매유형,기회시작일,공급가,금액(VAT별도)
0,서울1 IT코디센터,김민지,403-87-00573,(주)지엔오션,Bizbox Alpha Cloud,업셀,2019-04-17,12200000,100000
1,서울1 IT코디센터,송재웅,120-87-84760,주식회사 퀄슨,ICUBE 클라우드서버,신규,2019-04-17,0,3660000
2,엠아이솔루션,전지원,133-81-19093,디와이엘라센(주),ICUBE 클라우드서버,신규,2019-04-17,0,2640000
3,유니에스아이,박준호,211-88-68802,유한회사 알지피코리아,ICUBE 클라우드서버,신규,2019-04-17,0,5469600
4,중부IT코디센터,성민석,314-86-60600,주식회사 웰텍,Bizbox Alpha Cloud,추가,2019-04-17,20000,12000
5,호남IT코디센터,김기성,411-82-11004,(재)녹색에너지연구원,ICUBE 클라우드서버,신규,2019-04-17,0,3300000

In [40]:
pd.DataFrame(grouped_df.size().reset_index(name = "Group_Count"))

,영업채널명,영업담당자명,사업자/주민,고객명,상품명,판매유형,기회시작일,Group_Count
0,서울1 IT코디센터,김민지,403-87-00573,(주)지엔오션,Bizbox Alpha Cloud,업셀,2019-04-17,2
1,서울1 IT코디센터,송재웅,120-87-84760,주식회사 퀄슨,ICUBE 클라우드서버,신규,2019-04-17,5
2,엠아이솔루션,전지원,133-81-19093,디와이엘라센(주),ICUBE 클라우드서버,신규,2019-04-17,3
3,유니에스아이,박준호,211-88-68802,유한회사 알지피코리아,ICUBE 클라우드서버,신규,2019-04-17,4
4,중부IT코디센터,성민석,314-86-60600,주식회사 웰텍,Bizbox Alpha Cloud,추가,2019-04-17,1
5,호남IT코디센터,김기성,411-82-11004,(재)녹색에너지연구원,ICUBE 클라우드서버,신규,2019-04-17,4

In [41]:
pd.DataFrame(grouped_df['금액(VAT별도)'].sum().reset_index(name='총금액'))

,영업채널명,영업담당자명,사업자/주민,고객명,상품명,판매유형,기회시작일,총금액
0,서울1 IT코디센터,김민지,403-87-00573,(주)지엔오션,Bizbox Alpha Cloud,업셀,2019-04-17,100000
1,서울1 IT코디센터,송재웅,120-87-84760,주식회사 퀄슨,ICUBE 클라우드서버,신규,2019-04-17,3660000
2,엠아이솔루션,전지원,133-81-19093,디와이엘라센(주),ICUBE 클라우드서버,신규,2019-04-17,2640000
3,유니에스아이,박준호,211-88-68802,유한회사 알지피코리아,ICUBE 클라우드서버,신규,2019-04-17,5469600
4,중부IT코디센터,성민석,314-86-60600,주식회사 웰텍,Bizbox Alpha Cloud,추가,2019-04-17,12000
5,호남IT코디센터,김기성,411-82-11004,(재)녹색에너지연구원,ICUBE 클라우드서버,신규,2019-04-17,3300000

In [170]:
df2.groupby(['고객명', '상품명'], as_index=True)['금액(VAT별도)'].sum()

고객명          상품명
(재)녹색에너지연구원  ICUBE 클라우드서버          3300000
(주)지엔오션      Bizbox Alpha Cloud     100000
디와이엘라센(주)    ICUBE 클라우드서버          2640000
유한회사 알지피코리아  ICUBE 클라우드서버          5469600
주식회사 웰텍      Bizbox Alpha Cloud      12000
주식회사 퀄슨      ICUBE 클라우드서버          3660000
Name: 금액(VAT별도), dtype: int64

In [12]:
df2.groupby(groupby_columns_list, as_index=False)['금액(VAT별도)'].sum()

,영업채널명,영업담당자명,사업자/주민,고객명,상품명,판매유형,기회시작일,금액(VAT별도)
0,서울1 IT코디센터,김민지,403-87-00573,(주)지엔오션,Bizbox Alpha Cloud,업셀,2019-04-17,100000
1,서울1 IT코디센터,송재웅,120-87-84760,주식회사 퀄슨,ICUBE 클라우드서버,신규,2019-04-17,3660000
2,엠아이솔루션,전지원,133-81-19093,디와이엘라센(주),ICUBE 클라우드서버,신규,2019-04-17,2640000
3,유니에스아이,박준호,211-88-68802,유한회사 알지피코리아,ICUBE 클라우드서버,신규,2019-04-17,5469600
4,중부IT코디센터,성민석,314-86-60600,주식회사 웰텍,Bizbox Alpha Cloud,추가,2019-04-17,12000
5,호남IT코디센터,김기성,411-82-11004,(재)녹색에너지연구원,ICUBE 클라우드서버,신규,2019-04-17,3300000

In [277]:
dfg = df2.groupby(['고객명', '상품명'], as_index=False)

In [278]:
sum_df = dfg['금액(VAT별도)'].sum()

In [326]:
df2.apply(lambda row: row)

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,공급가,금액(VAT별도),판매유형,기회시작일
3,"서울1,2 IT코디센터",서울1 IT코디센터,김민지,(주)지엔오션,403-87-00573,2019-04-17,주문완료,주문완료,일시납,Bizbox Alpha Cloud,"엔진(기본, 웹메일)",12000000,0,업셀,2019-04-17
4,"서울1,2 IT코디센터",서울1 IT코디센터,김민지,(주)지엔오션,403-87-00573,2019-04-17,주문완료,주문완료,일시납,Bizbox Alpha Cloud,유저 라이선스(월납),200000,100000,업셀,2019-04-17
5,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1200000,신규,2019-04-17
6,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백신서비스(서버전용백신),0,360000,신규,2019-04-17
7,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
8,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
9,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
31,중부IT코디센터,중부IT코디센터,성민석,주식회사 웰텍,314-86-60600,2019-04-17,진행중,진행중,일시납,Bizbox Alpha Cloud,유저 라이선스(월납),20000,12000,추가,2019-04-17
32,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1200000,신규,2019-04-17
33,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
34,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
35,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
43,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1080000,신규,2019-04-17
44,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
45,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
46,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,3369600,신규,2019-04-17
47,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
48,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
49,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17

In [230]:
for name, group in grouped_df:
    ix = grouped_df.indices[name]
    #print(type(group))
    #print(group.loc[:,'영업담당자명'])
    #print(group)
    print("index {0} : {1}".format(ix, name))
    print("-"*20)
    for cname in group:
        print("{0} : {1}".format(cname, group[cname]))

index [ 8  9 10 11] : ('(재)녹색에너지연구원', 'ICUBE 클라우드서버')
--------------------
주담당채널 : 32    호남IT코디센터
33    호남IT코디센터
34    호남IT코디센터
35    호남IT코디센터
Name: 주담당채널, dtype: object
영업채널명 : 32    호남IT코디센터
33    호남IT코디센터
34    호남IT코디센터
35    호남IT코디센터
Name: 영업채널명, dtype: object
영업담당자명 : 32    김기성
33    김기성
34    김기성
35    김기성
Name: 영업담당자명, dtype: object
고객명 : 32    (재)녹색에너지연구원
33    (재)녹색에너지연구원
34    (재)녹색에너지연구원
35    (재)녹색에너지연구원
Name: 고객명, dtype: object
사업자/주민 : 32    411-82-11004
33    411-82-11004
34    411-82-11004
35    411-82-11004
Name: 사업자/주민, dtype: object
주문일자 : 32    2019-04-17
33    2019-04-17
34    2019-04-17
35    2019-04-17
Name: 주문일자, dtype: object
주문상태 : 32    주문완료
33    주문완료
34    주문완료
35    주문완료
Name: 주문상태, dtype: object
주문현황 : 32    발송중
33    발송중
34    발송중
35    발송중
Name: 주문현황, dtype: object
납입구분 : 32    일시납
33    일시납
34    일시납
35    일시납
Name: 납입구분, dtype: object
상품명 : 32    ICUBE 클라우드서버
33    ICUBE 클라우드서버
34    ICUBE 클라우드서버
35    ICUBE 클라우드서버
Name: 상품명, dtype: object
단위상품명 : 32            클라우드서버(기본)
33    MS SQL for DOUZONE
34                 보안서비스
35                 백업서비스
Name: 단위상품명, dtype: object
공급가 : 32    0
33    0
34    0
35    0
Name: 공급가, dtype: int64
금액(VAT별도) : 32    1200000
33     960000
34     600000
35     540000
Name: 금액(VAT별도), dtype: int64
판매유형 : 32    신규
33    신규
34    신규
35    신규
Name: 판매유형, dtype: object
기회시작일 : 32    2019-04-17
33    2019-04-17
34    2019-04-17
35    2019-04-17
Name: 기회시작일, dtype: object
index [0 1] : ('(주)지엔오션', 'Bizbox Alpha Cloud')
--------------------
주담당채널 : 3    서울1,2 IT코디센터
4    서울1,2 IT코디센터
Name: 주담당채널, dtype: object
영업채널명 : 3    서울1 IT코디센터
4    서울1 IT코디센터
Name: 영업채널명, dtype: object
영업담당자명 : 3    김민지
4    김민지
Name: 영업담당자명, dtype: object
고객명 : 3    (주)지엔오션
4    (주)지엔오션
Name: 고객명, dtype: object
사업자/주민 : 3    403-87-00573
4    403-87-00573
Name: 사업자/주민, dtype: object
주문일자 : 3    2019-04-17
4    2019-04-17
Name: 주문일자, dtype: object
주문상태 : 3    주문완료
4    주문완료
Name: 주문상태, dtype: object
주문현황 : 3    주문완료
4    주문완료
Name: 주문현황, dtype: object
납입구분 : 3    일시납
4    일시납
Name: 납입구분, dtype: object
상품명 : 3    Bizbox Alpha Cloud
4    Bizbox Alpha Cloud
Name: 상품명, dtype: object
단위상품명 : 3    엔진(기본, 웹메일)
4    유저 라이선스(월납)
Name: 단위상품명, dtype: object
공급가 : 3    12000000
4      200000
Name: 공급가, dtype: int64
금액(VAT별도) : 3         0
4    100000
Name: 금액(VAT별도), dtype: int64
판매유형 : 3    업셀
4    업셀
Name: 판매유형, dtype: object
기회시작일 : 3    2019-04-17
4    2019-04-17
Name: 기회시작일, dtype: object
index [12 13 14] : ('디와이엘라센(주)', 'ICUBE 클라우드서버')
--------------------
주담당채널 : 43    NaN
44    NaN
45    NaN
Name: 주담당채널, dtype: object
영업채널명 : 43    엠아이솔루션
44    엠아이솔루션
45    엠아이솔루션
Name: 영업채널명, dtype: object
영업담당자명 : 43    전지원
44    전지원
45    전지원
Name: 영업담당자명, dtype: object
고객명 : 43    디와이엘라센(주)
44    디와이엘라센(주)
45    디와이엘라센(주)
Name: 고객명, dtype: object
사업자/주민 : 43    133-81-19093
44    133-81-19093
45    133-81-19093
Name: 사업자/주민, dtype: object
주문일자 : 43    2019-04-17
44    2019-04-17
45    2019-04-17
Name: 주문일자, dtype: object
주문상태 : 43    진행중
44    진행중
45    진행중
Name: 주문상태, dtype: object
주문현황 : 43    진행중
44    진행중
45    진행중
Name: 주문현황, dtype: object
납입구분 : 43    일시납
44    일시납
45    일시납
Name: 납입구분, dtype: object
상품명 : 43    ICUBE 클라우드서버
44    ICUBE 클라우드서버
45    ICUBE 클라우드서버
Name: 상품명, dtype: object
단위상품명 : 43            클라우드서버(기본)
44                 보안서비스
45    MS SQL for DOUZONE
Name: 단위상품명, dtype: object
공급가 : 43    0
44    0
45    0
Name: 공급가, dtype: int64
금액(VAT별도) : 43    1080000
44     600000
45     960000
Name: 금액(VAT별도), dtype: int64
판매유형 : 43    신규
44    신규
45    신규
Name: 판매유형, dtype: object
기회시작일 : 43    2019-04-17
44    2019-04-17
45    2019-04-17
Name: 기회시작일, dtype: object
index [15 16 17 18] : ('유한회사 알지피코리아', 'ICUBE 클라우드서버')
--------------------
주담당채널 : 46    NaN
47    NaN
48    NaN
49    NaN
Name: 주담당채널, dtype: object
영업채널명 : 46    유니에스아이
47    유니에스아이
48    유니에스아이
49    유니에스아이
Name: 영업채널명, dtype: object
영업담당자명 : 46    박준호
47    박준호
48    박준호
49    박준호
Name: 영업담당자명, dtype: object
고객명 : 46    유한회사 알지피코리아
47    유한회사 알지피코리아
48    유한회사 알지피코리아
49    유한회사 알지피코리아
Name: 고객명, dtype: object
사업자/주민 : 46    211-88-68802
47    211-88-68802
48    211-88-68802
49    211-88-68802
Name: 사업자/주민, dtype: object
주문일자 : 46    2019-04-17
47    2019-04-17
48    2019-04-17
49    2019-04-17
Name: 주문일자, dtype: object
주문상태 : 46    주문완료
47    주문완료
48    주문완료
49    주문완료
Name: 주문상태, dtype: object
주문현황 : 46    주문완료
47    주문완료
48    주문완료
49    주문완료
Name: 주문현황, dtype: object
납입구분 : 46    일시납
47    일시납
48    일시납
49    일시납
Name: 납입구분, dtype: object
상품명 : 46    ICUBE 클라우드서버
47    ICUBE 클라우드서버
48    ICUBE 클라우드서버
49    ICUBE 클라우드서버
Name: 상품명, dtype: object
단위상품명 : 46            클라우드서버(기본)
47                 백업서비스
48                 보안서비스
49    MS SQL for DOUZONE
Name: 단위상품명, dtype: object
공급가 : 46    0
47    0
48    0
49    0
Name: 공급가, dtype: int64
금액(VAT별도) : 46    3369600
47     540000
48     600000
49     960000
Name: 금액(VAT별도), dtype: int64
판매유형 : 46    신규
47    신규
48    신규
49    신규
Name: 판매유형, dtype: object
기회시작일 : 46    2019-04-17
47    2019-04-17
48    2019-04-17
49    2019-04-17
Name: 기회시작일, dtype: object
index [7] : ('주식회사 웰텍', 'Bizbox Alpha Cloud')
--------------------
주담당채널 : 31    중부IT코디센터
Name: 주담당채널, dtype: object
영업채널명 : 31    중부IT코디센터
Name: 영업채널명, dtype: object
영업담당자명 : 31    성민석
Name: 영업담당자명, dtype: object
고객명 : 31    주식회사 웰텍
Name: 고객명, dtype: object
사업자/주민 : 31    314-86-60600
Name: 사업자/주민, dtype: object
주문일자 : 31    2019-04-17
Name: 주문일자, dtype: object
주문상태 : 31    진행중
Name: 주문상태, dtype: object
주문현황 : 31    진행중
Name: 주문현황, dtype: object
납입구분 : 31    일시납
Name: 납입구분, dtype: object
상품명 : 31    Bizbox Alpha Cloud
Name: 상품명, dtype: object
단위상품명 : 31    유저 라이선스(월납)
Name: 단위상품명, dtype: object
공급가 : 31    20000
Name: 공급가, dtype: int64
금액(VAT별도) : 31    12000
Name: 금액(VAT별도), dtype: int64
판매유형 : 31    추가
Name: 판매유형, dtype: object
기회시작일 : 31    2019-04-17
Name: 기회시작일, dtype: object
index [2 3 4 5 6] : ('주식회사 퀄슨', 'ICUBE 클라우드서버')
--------------------
주담당채널 : 5    서울1,2 IT코디센터
6    서울1,2 IT코디센터
7    서울1,2 IT코디센터
8    서울1,2 IT코디센터
9    서울1,2 IT코디센터
Name: 주담당채널, dtype: object
영업채널명 : 5    서울1 IT코디센터
6    서울1 IT코디센터
7    서울1 IT코디센터
8    서울1 IT코디센터
9    서울1 IT코디센터
Name: 영업채널명, dtype: object
영업담당자명 : 5    송재웅
6    송재웅
7    송재웅
8    송재웅
9    송재웅
Name: 영업담당자명, dtype: object
고객명 : 5    주식회사 퀄슨
6    주식회사 퀄슨
7    주식회사 퀄슨
8    주식회사 퀄슨
9    주식회사 퀄슨
Name: 고객명, dtype: object
사업자/주민 : 5    120-87-84760
6    120-87-84760
7    120-87-84760
8    120-87-84760
9    120-87-84760
Name: 사업자/주민, dtype: object
주문일자 : 5    2019-04-17
6    2019-04-17
7    2019-04-17
8    2019-04-17
9    2019-04-17
Name: 주문일자, dtype: object
주문상태 : 5    주문완료
6    주문완료
7    주문완료
8    주문완료
9    주문완료
Name: 주문상태, dtype: object
주문현황 : 5    주문완료
6    주문완료
7    주문완료
8    주문완료
9    주문완료
Name: 주문현황, dtype: object
납입구분 : 5    일시납
6    일시납
7    일시납
8    일시납
9    일시납
Name: 납입구분, dtype: object
상품명 : 5    ICUBE 클라우드서버
6    ICUBE 클라우드서버
7    ICUBE 클라우드서버
8    ICUBE 클라우드서버
9    ICUBE 클라우드서버
Name: 상품명, dtype: object
단위상품명 : 5            클라우드서버(기본)
6         백신서비스(서버전용백신)
7                 백업서비스
8                 보안서비스
9    MS SQL for DOUZONE
Name: 단위상품명, dtype: object
공급가 : 5    0
6    0
7    0
8    0
9    0
Name: 공급가, dtype: int64
금액(VAT별도) : 5    1200000
6     360000
7     540000
8     600000
9     960000
Name: 금액(VAT별도), dtype: int64
판매유형 : 5    신규
6    신규
7    신규
8    신규
9    신규
Name: 판매유형, dtype: object
기회시작일 : 5    2019-04-17
6    2019-04-17
7    2019-04-17
8    2019-04-17
9    2019-04-17
Name: 기회시작일, dtype: object

In [232]:
s1 = df2.iloc[15]

In [238]:
df2

,주담당채널,영업채널명,영업담당자명,고객명,사업자/주민,주문일자,주문상태,주문현황,납입구분,상품명,단위상품명,공급가,금액(VAT별도),판매유형,기회시작일
3,"서울1,2 IT코디센터",서울1 IT코디센터,김민지,(주)지엔오션,403-87-00573,2019-04-17,주문완료,주문완료,일시납,Bizbox Alpha Cloud,"엔진(기본, 웹메일)",12000000,0,업셀,2019-04-17
4,"서울1,2 IT코디센터",서울1 IT코디센터,김민지,(주)지엔오션,403-87-00573,2019-04-17,주문완료,주문완료,일시납,Bizbox Alpha Cloud,유저 라이선스(월납),200000,100000,업셀,2019-04-17
5,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1200000,신규,2019-04-17
6,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백신서비스(서버전용백신),0,360000,신규,2019-04-17
7,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
8,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
9,"서울1,2 IT코디센터",서울1 IT코디센터,송재웅,주식회사 퀄슨,120-87-84760,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
31,중부IT코디센터,중부IT코디센터,성민석,주식회사 웰텍,314-86-60600,2019-04-17,진행중,진행중,일시납,Bizbox Alpha Cloud,유저 라이선스(월납),20000,12000,추가,2019-04-17
32,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1200000,신규,2019-04-17
33,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
34,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
35,호남IT코디센터,호남IT코디센터,김기성,(재)녹색에너지연구원,411-82-11004,2019-04-17,주문완료,발송중,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
43,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,1080000,신규,2019-04-17
44,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
45,NaN,엠아이솔루션,전지원,디와이엘라센(주),133-81-19093,2019-04-17,진행중,진행중,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17
46,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,클라우드서버(기본),0,3369600,신규,2019-04-17
47,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,백업서비스,0,540000,신규,2019-04-17
48,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,보안서비스,0,600000,신규,2019-04-17
49,NaN,유니에스아이,박준호,유한회사 알지피코리아,211-88-68802,2019-04-17,주문완료,주문완료,일시납,ICUBE 클라우드서버,MS SQL for DOUZONE,0,960000,신규,2019-04-17

In [236]:
s1

주담당채널                 NaN
영업채널명              유니에스아이
영업담당자명                박준호
고객명           유한회사 알지피코리아
사업자/주민       211-88-68802
주문일자           2019-04-17
주문상태                 주문완료
주문현황                 주문완료
납입구분                  일시납
상품명          ICUBE 클라우드서버
단위상품명          클라우드서버(기본)
공급가                     0
금액(VAT별도)         3369600
판매유형                   신규
기회시작일          2019-04-17
Name: 46, dtype: object